PERCORSO_FILE_EXCEL = "libriAndrea.xlsm"
NOME_FOGLIO = "lista"
PRIMA_RIGA_TABELLA = 2
COLONNA_ISBN = 1
COLONNA_AUTORI = 3
COLONNA_TITOLO = 4
COLONNA_DATA = 5
COLONNA_CONTROLLO_RIGA_COMPILATA = COLONNA_AUTORI
